# Generated by Django 3.2.8 on 2021-11-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('director', 'Director'), ('project_menager', 'Project Menager')], max_length=30, null=True),
        ),
    ]
