# Generated by Django 3.2.8 on 2021-11-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('director', 'Director'), ('project_menager', 'Project menager')], max_length=20, null=True),
        ),
    ]
