# Generated by Django 3.2.8 on 2021-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20211104_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('director_products', 'Products Director'), ('director_services', 'Services Director'), ('project_menager', 'Project Menager')], max_length=30, null=True),
        ),
    ]
