# Generated by Django 3.2.8 on 2021-12-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('accounts', 'Accounts'), ('director', 'Director'), ('project_menager', 'Project Menager')], max_length=30, null=True),
        ),
    ]
