<<<<<<< HEAD:documents/migrations/0002_auto_20211101_1518.py
# Generated by Django 3.2.8 on 2021-11-01 14:18
=======
# Generated by Django 3.2.8 on 2021-11-02 11:35
>>>>>>> 50d1113df6d65a0ec1fde7837d4c41f922645106:documents/migrations/0002_auto_20211102_1135.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
