# Generated by Django 3.2.8 on 2021-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, choices=[('product', 'Product'), ('service', 'Service')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
