# Generated by Django 3.2.8 on 2021-11-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20211104_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='test',
        ),
    ]
