# Generated by Django 3.2.8 on 2021-11-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_assignment_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='approved',
            new_name='approved_director',
        ),
        migrations.AddField(
            model_name='document',
            name='approved_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
