# Generated by Django 3.2.8 on 2021-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20211105_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Divided'), ('2', 'Waiting for checks'), ('3', 'Checked'), ('4', 'Approved'), ('5', 'Waiting for payment'), ('6', 'Paid')], max_length=50, null=True),
        ),
    ]
