# Generated by Django 3.2.8 on 2021-10-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
