# Generated by Django 3.2.8 on 2021-11-05 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_position'),
        ('documents', '0007_auto_20211105_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(blank=True, choices=[], null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
