# Generated by Django 3.2.8 on 2021-11-05 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_position'),
        ('documents', '0008_alter_assignment_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'project_menager'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
