# Generated by Django 3.2.8 on 2021-10-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
