# Generated by Django 3.2.8 on 2021-12-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('Assigned to director', 'Assigned to director'), ('Waiting', 'Waiting for checks'), ('Checked', 'Checked'), ('Waiting for payment', 'Waiting for payment'), ('Paid', 'Paid')], max_length=50, null=True),
        ),
    ]
