# Generated by Django 3.2.8 on 2021-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_project_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
