# Generated by Django 3.2.8 on 2021-12-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='title', max_length=250),
        ),
    ]
