# Generated by Django 3.2.8 on 2021-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
