# Generated by Django 3.2.8 on 2021-10-29 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20211029_1004'),
        ('documents', '0017_assignment'),
    ]

    operations = [
    ]
