# Generated by Django 3.2.8 on 2021-10-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_merge_0002_auto_20211029_1004_0017_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
