# Generated by Django 3.2.8 on 2022-01-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, choices=[('Waiting for assignment to PM', 'Waiting for assignment to PM'), ('Waiting for checks', 'Waiting for checks'), ('Waiting for director to approve', 'Waiting for director to approve'), ('Waiting for payment', 'Waiting for payment'), ('Paid', 'Paid')], max_length=50, null=True),
        ),
    ]
