# Generated by Django 3.2.8 on 2022-01-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_alter_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='approved_director',
        ),
        migrations.RemoveField(
            model_name='document',
            name='approved_pm',
        ),
    ]
