# Generated by Django 3.2.8 on 2022-01-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, choices=[('product', 'Product'), ('service', 'Service')], default='', max_length=30),
        ),
    ]
